table department_fiscal_year_spend
	isHidden
	lineageTag: c0433132-0238-4683-b524-76df5fbfc4a2

	column department_name
		dataType: string
		lineageTag: a6dc81c8-42fc-4f9d-a0a5-54af3b94d555
		summarizeBy: none
		sourceColumn: department_name

		annotation SummarizationSetBy = Automatic

	column business_unit
		dataType: string
		lineageTag: 5d52f26c-94dc-45af-9189-9ee99c68213f
		summarizeBy: none
		sourceColumn: business_unit

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: int64
		lineageTag: 770dc3be-c095-4563-b1b6-f5aaab554def
		summarizeBy: none
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	column document_count
		dataType: int64
		lineageTag: 06e021d9-7044-49a0-825c-a32175e2aada
		summarizeBy: sum
		sourceColumn: document_count

		annotation SummarizationSetBy = Automatic

	column total_value
		dataType: double
		lineageTag: 22333d9b-3771-4fdd-890d-a497faccf8f5
		summarizeBy: sum
		sourceColumn: total_value

		annotation SummarizationSetBy = Automatic

	partition department_fiscal_year_spend = m
		mode: import
		source =
				let
					Source = LoadMart("department_fiscal_year_spend"),
					Typed = Table.TransformColumnTypes(Source, {
						{"department_name", type text},
						{"business_unit", type text},
						{"fiscal_year", Int64.Type},
						{"document_count", Int64.Type},
						{"total_value", type number}
					}, "en-US")
				in
					Typed

	annotation PBI_ResultType = Table
