table dim_date
	lineageTag: 244f03ea-ef78-4931-ab89-cd12c97287e5
	dataCategory: Time

	column date_key
		dataType: int64
		isHidden
		lineageTag: 273f76c8-8cc1-4bb7-a158-23b3f1c52b90
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column full_date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: a86bb92c-3db9-48e0-a58b-0b3d1646a853
		summarizeBy: none
		sourceColumn: full_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		lineageTag: c0bd8d5a-88a5-40e7-9720-78695b59f4ba
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		lineageTag: b3c89cd8-e89a-4fe7-aa97-3fc945a9a873
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		lineageTag: 3d113635-de93-4538-b2f2-845ca5096b67
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: e8cd4d54-bb8c-416c-9564-caa92d49ba20
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		lineageTag: 4d688758-3168-4439-b8df-15f569fc487d
		summarizeBy: none
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: string
		lineageTag: 40cc07bb-a7de-41c6-a74b-6d81e1645f91
		summarizeBy: none
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: int64
		lineageTag: 4fbe8b19-4756-4508-a99d-5c36b8fbbc0a
		summarizeBy: none
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	column fiscal_quarter
		dataType: int64
		lineageTag: b30b03da-3fdd-4d17-92e1-7943da9f7ced
		summarizeBy: none
		sourceColumn: fiscal_quarter

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
					Source = LoadStar("dim_date"),
					Typed = Table.TransformColumnTypes(Source, {
						{"full_date", type date},
						{"year", Int64.Type},
						{"quarter", Int64.Type},
						{"month", Int64.Type},
						{"day", Int64.Type},
						{"fiscal_year", Int64.Type},
						{"fiscal_quarter", Int64.Type}
					}),
					// the star's unknown-date member (date_key 0) has a null full_date,
					// which a marked date table must not carry
					NoUnknown = Table.SelectRows(Typed, each [full_date] <> null)
				in
					NoUnknown

	annotation PBI_ResultType = Table
