table gold_monthly_spend
	isHidden
	lineageTag: f812bf73-501d-4b17-89fe-485d5d990987

	column year
		dataType: double
		lineageTag: a5b486f1-25a6-481b-b189-43b1cb706e83
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column month
		dataType: double
		lineageTag: a23151b6-aff1-4b3b-aa47-1af631b9f00d
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 7304335d-dbc1-4f3b-89b8-3993115ed2c3
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column document_count
		dataType: int64
		lineageTag: 8bdac66f-426f-4033-868b-6f0e66709b5c
		summarizeBy: sum
		sourceColumn: document_count

		annotation SummarizationSetBy = Automatic

	column total_value
		dataType: double
		lineageTag: 3b1ae413-25a6-415a-b565-d49a7a94a5ef
		summarizeBy: sum
		sourceColumn: total_value

		annotation SummarizationSetBy = Automatic

	partition gold_monthly_spend = m
		mode: import
		source =
				let
					Source = LoadMart("gold_monthly_spend"),
					Typed = Table.TransformColumnTypes(Source, {
						{"year", type number},
						{"month", type number},
						{"month_name", type text},
						{"document_count", Int64.Type},
						{"total_value", type number}
					}, "en-US")
				in
					Typed

	annotation PBI_ResultType = Table
