table gold_supplier_acquisition_profile
	lineageTag: a9d67d9f-1759-4742-bb67-f9f7941f4f54

	column supplier_id
		dataType: string
		lineageTag: 6e24cc80-fc29-4a0c-9aa7-392a836c6e1b
		summarizeBy: none
		sourceColumn: supplier_id

		annotation SummarizationSetBy = Automatic

	column supplier_name
		dataType: string
		lineageTag: 1383bfbd-bc31-4e24-97b0-7c86540acf29
		summarizeBy: none
		sourceColumn: supplier_name

		annotation SummarizationSetBy = Automatic

	column acquisition_type
		dataType: string
		lineageTag: 17a17611-7ba1-4839-b943-29178bebf0d8
		summarizeBy: none
		sourceColumn: acquisition_type

		annotation SummarizationSetBy = Automatic

	column document_count
		dataType: int64
		lineageTag: e6f33f4f-e3eb-40b9-9b18-a7d81cbf8bba
		summarizeBy: sum
		sourceColumn: document_count

		annotation SummarizationSetBy = Automatic

	column total_value
		dataType: double
		lineageTag: 6afa4730-608f-4d69-91aa-383f2c5e3614
		summarizeBy: sum
		sourceColumn: total_value

		annotation SummarizationSetBy = Automatic

	partition gold_supplier_acquisition_profile = m
		mode: import
		source =
				let
					Source = LoadMart("gold_supplier_acquisition_profile"),
					Typed = Table.TransformColumnTypes(Source, {
						{"supplier_id", type text},
						{"supplier_name", type text},
						{"acquisition_type", type text},
						{"document_count", Int64.Type},
						{"total_value", type number}
					}, "en-US")
				in
					Typed

	annotation PBI_ResultType = Table
