table gold_acquisition_spend
	lineageTag: 85ca7067-9316-4c8b-bae9-fde4853afc6f

	column acquisition_type
		dataType: string
		lineageTag: b06f6645-0fcc-4d63-b72d-e53306eec7aa
		summarizeBy: none
		sourceColumn: acquisition_type

		annotation SummarizationSetBy = Automatic

	column acquisition_method
		dataType: string
		lineageTag: 8fc7a04a-8b56-47d3-a2ec-81ddfb6dbd1e
		summarizeBy: none
		sourceColumn: acquisition_method

		annotation SummarizationSetBy = Automatic

	column competitive_flag
		dataType: string
		lineageTag: b8440532-f97e-42b1-b348-cf064f273ed5
		summarizeBy: none
		sourceColumn: competitive_flag

		annotation SummarizationSetBy = Automatic

	column document_count
		dataType: int64
		lineageTag: c03efbeb-b21e-4aa3-a191-60d05d9ee69c
		summarizeBy: sum
		sourceColumn: document_count

		annotation SummarizationSetBy = Automatic

	column total_value
		dataType: double
		lineageTag: fa118ac9-0a87-4d03-be4c-2d1beb350948
		summarizeBy: sum
		sourceColumn: total_value

		annotation SummarizationSetBy = Automatic

	partition gold_acquisition_spend = m
		mode: import
		source =
				let
					Source = LoadMart("gold_acquisition_spend"),
					Typed = Table.TransformColumnTypes(Source, {
						{"acquisition_type", type text},
						{"acquisition_method", type text},
						{"competitive_flag", type text},
						{"document_count", Int64.Type},
						{"total_value", type number}
					}, "en-US")
				in
					Typed

	annotation PBI_ResultType = Table
