table gold_eprocure_event_demand
	lineageTag: beea25e9-a7ac-4439-9ef9-5fcb5abe3793

	column department_name
		dataType: string
		lineageTag: 773cbeb1-831e-4a68-a6f0-c011ac7224da
		summarizeBy: none
		sourceColumn: department_name

		annotation SummarizationSetBy = Automatic

	column business_unit
		dataType: string
		lineageTag: 7ee2c50b-faa2-4550-96e2-a0eb94062f54
		summarizeBy: none
		sourceColumn: business_unit

		annotation SummarizationSetBy = Automatic

	column event_year
		dataType: int64
		lineageTag: b3bba690-a3e8-4085-be2e-287b1f493511
		summarizeBy: none
		sourceColumn: event_year

		annotation SummarizationSetBy = Automatic

	column event_count
		dataType: int64
		lineageTag: 84636d68-b46c-47cc-8b1c-e5c6e5d05dff
		summarizeBy: sum
		sourceColumn: event_count

		annotation SummarizationSetBy = Automatic

	column sb_only_count
		dataType: int64
		lineageTag: ba57cfe4-c35e-4c29-ab25-ac0d460ed0ef
		summarizeBy: sum
		sourceColumn: sb_only_count

		annotation SummarizationSetBy = Automatic

	column dvbe_only_count
		dataType: int64
		lineageTag: 88624de3-7ade-472d-9bc9-6ba9b450cc79
		summarizeBy: sum
		sourceColumn: dvbe_only_count

		annotation SummarizationSetBy = Automatic

	column set_aside_pct
		dataType: double
		lineageTag: 36030901-8064-4139-a1cd-6c7cba0f42c0
		summarizeBy: none
		sourceColumn: set_aside_pct

		annotation SummarizationSetBy = Automatic

	partition gold_eprocure_event_demand = m
		mode: import
		source =
				let
					Source = LoadMart("gold_eprocure_event_demand"),
					Typed = Table.TransformColumnTypes(Source, {
						{"department_name", type text},
						{"business_unit", type text},
						{"event_year", Int64.Type},
						{"event_count", Int64.Type},
						{"sb_only_count", Int64.Type},
						{"dvbe_only_count", Int64.Type},
						{"set_aside_pct", type number}
					}, "en-US")
				in
					Typed

	annotation PBI_ResultType = Table
