"""Warehouse output diff for pull requests — Wave 3 (continuous delivery).

The bronze/silver/gold build is a full refresh of SQL generated by Python, so a
change to `warehouse.py` (a mart, a grain, an abbreviation, a join) can silently
shift the *output* — drop rows, rename a mart column, change an aggregate — in ways
a unit test on a 3-row fixture won't catch. This tool builds the warehouse from the
**same real operational data** on two code versions and reports how gold changed,
so a reviewer sees the data impact of a warehouse PR before merging.

It runs in two steps so the *same* (head) tool snapshots both builds:

    python -m src.warehouse_diff snapshot --db data/warehouse.db --out head.json
    #   (CI rebuilds with the base code, same data) ...
    python -m src.warehouse_diff snapshot --db data/warehouse.db --out base.json
    python -m src.warehouse_diff report --base base.json --head head.json

A snapshot captures three contract surfaces:
  * **objects** — the gold/dim/fact tables and views that exist (added/removed),
  * **columns** — each object's column list (mart output names are the API),
  * **metrics** — a curated set of headline aggregates (row counts, total spend,
    supplier counts, CMAS coverage), queried through the logical-named `lv_`/`gold_`
    views so abbreviation changes don't perturb them.

The report is **informational, not a gate**: warehouse output changes are often
intended (a new mart, more enriched rows). It flags the shapes worth a second look
(removed objects/columns, large row-count drops) with ⚠️ so they catch the eye.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path

# Headline metrics, each a single-value SELECT over logical-named views so the
# abbreviation pass never perturbs them. A metric that errors (e.g. a mart removed)
# records None and shows up as a change in the report.
_METRICS: dict[str, str] = {
    "fact_document_rows": "SELECT COUNT(*) FROM fact_document",
    "fact_line_rows": "SELECT COUNT(*) FROM fact_line",
    "fact_associated_po_rows": "SELECT COUNT(*) FROM fact_associated_po",
    "total_grand_total": "SELECT ROUND(SUM(grand_total), 2) FROM lv_fact_document",
    "total_line_amount": "SELECT ROUND(SUM(line_amount), 2) FROM lv_fact_line",
    "supplier_registrations": "SELECT COUNT(*) FROM dim_supplier",
    "canonical_suppliers": "SELECT COUNT(DISTINCT canonical_id) FROM lv_dim_supplier",
    "departments": "SELECT COUNT(*) FROM dim_department",
    "cmas_agreements": "SELECT COUNT(*) FROM gold_cmas_agreement",
    "cmas_matched_suppliers": "SELECT COUNT(*) FROM gold_supplier_cmas",
}

# A row-count drop beyond this fraction is flagged (intentional shrinks happen, but
# they deserve a reviewer's eye).
_DROP_FLAG = 0.02


def snapshot(db_path: Path) -> dict:
    """Capture the gold output contract of a built warehouse as a plain dict."""
    con = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        objects = [
            r[0]
            for r in con.execute(
                "SELECT name FROM sqlite_master WHERE type IN ('table','view') AND "
                "(name LIKE 'gold_%' OR name LIKE 'dim_%' OR name LIKE 'fact_%') ORDER BY name"
            )
        ]
        columns: dict[str, list[str]] = {}
        row_counts: dict[str, int | None] = {}
        for obj in objects:
            columns[obj] = [r[1] for r in con.execute(f'PRAGMA table_info("{obj}")')]
            row_counts[obj] = _scalar(con, f'SELECT COUNT(*) FROM "{obj}"')  # noqa: S608
        metrics = {name: _scalar(con, sql) for name, sql in _METRICS.items()}
        return {
            "objects": objects,
            "columns": columns,
            "row_counts": row_counts,
            "metrics": metrics,
        }
    finally:
        con.close()


def _scalar(con: sqlite3.Connection, sql: str):
    try:
        row = con.execute(sql).fetchone()
        return row[0] if row else None
    except sqlite3.Error:
        return None


def report(base: dict, head: dict) -> str:
    """Render a markdown diff of two snapshots (base → head)."""
    out: list[str] = ["## 📊 Warehouse output diff", ""]
    flags: list[str] = []

    base_objs, head_objs = set(base["objects"]), set(head["objects"])
    added, removed = sorted(head_objs - base_objs), sorted(base_objs - head_objs)
    if added or removed:
        out.append("### Objects")
        for o in added:
            out.append(f"- 🟢 added `{o}`")
        for o in removed:
            out.append(f"- 🔴 removed `{o}`")
            flags.append(f"removed object `{o}`")
        out.append("")

    # Column changes on objects present in both.
    col_lines: list[str] = []
    for obj in sorted(base_objs & head_objs):
        b, h = set(base["columns"].get(obj, [])), set(head["columns"].get(obj, []))
        cadd, crem = sorted(h - b), sorted(b - h)
        if cadd or crem:
            parts = [f"+`{c}`" for c in cadd] + [f"−`{c}`" for c in crem]
            col_lines.append(f"- `{obj}`: {', '.join(parts)}")
            if crem:
                flags.append(f"`{obj}` dropped column(s) {', '.join(crem)}")
    if col_lines:
        out.append("### Columns")
        out.extend(col_lines)
        out.append("")

    # Row-count changes on objects present in both.
    rc_lines: list[str] = []
    for obj in sorted(base_objs & head_objs):
        b, h = base["row_counts"].get(obj), head["row_counts"].get(obj)
        if b == h or b is None or h is None:
            continue
        delta = h - b
        pct = (delta / b * 100) if b else float("inf")
        mark = ""
        if b and delta < 0 and abs(delta) / b > _DROP_FLAG:
            mark = " ⚠️"
            flags.append(f"`{obj}` rows {b:,} → {h:,} ({pct:+.1f}%)")
        rc_lines.append(f"- `{obj}`: {b:,} → {h:,} ({delta:+,}, {pct:+.1f}%){mark}")
    if rc_lines:
        out.append("### Row counts")
        out.extend(rc_lines)
        out.append("")

    # Metric changes.
    m_lines: list[str] = []
    for name in _METRICS:
        b, h = base["metrics"].get(name), head["metrics"].get(name)
        if b == h:
            continue
        m_lines.append(f"- `{name}`: {_fmt(b)} → {_fmt(h)}")
    if m_lines:
        out.append("### Headline metrics")
        out.extend(m_lines)
        out.append("")

    if flags:
        out.append("### ⚠️ Worth a look")
        out.extend(f"- {f}" for f in flags)
        out.append("")
    if len(out) <= 2:
        out.append("_No change to gold objects, columns, row counts, or headline metrics._")
    return "\n".join(out)


def _fmt(v) -> str:
    if v is None:
        return "—"
    if isinstance(v, float):
        return f"{v:,.2f}"
    if isinstance(v, int):
        return f"{v:,}"
    return str(v)


def _cli() -> None:
    ap = argparse.ArgumentParser(description="Diff warehouse gold output across two builds.")
    sub = ap.add_subparsers(dest="cmd", required=True)
    snp = sub.add_parser("snapshot", help="Capture a built warehouse's gold contract to JSON")
    snp.add_argument("--db", type=Path, required=True)
    snp.add_argument("--out", type=Path, required=True)
    rep = sub.add_parser("report", help="Render a markdown diff of two snapshots")
    rep.add_argument("--base", type=Path, required=True)
    rep.add_argument("--head", type=Path, required=True)
    args = ap.parse_args()

    if args.cmd == "snapshot":
        args.out.write_text(json.dumps(snapshot(args.db), indent=1), encoding="utf-8")
        print(f"snapshot -> {args.out}")
    elif args.cmd == "report":
        base = json.loads(args.base.read_text(encoding="utf-8"))
        head = json.loads(args.head.read_text(encoding="utf-8"))
        print(report(base, head))


if __name__ == "__main__":
    _cli()
